version: '3.8'

services:
  ecommerce-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=ecommerce
      - JWT_SECRET=your-super-secret-jwt-key-here
      - PORT=8080
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
