name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[test]') || contains(github.event.head_commit.message, '[run-tests]')
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Go application
      run: |
        go mod download
        go build -o ecommerce-backend main.go
    
    - name: Upload binary to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "ecommerce-backend"
        target: "/www/wwwroot/ecommerce-backend/ecommerce-backend.new"
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Suppress hostname warning (harmless)
          export DEBIAN_FRONTEND=noninteractive
          
          # Create directory if it doesn't exist (aaPanel structure)
          mkdir -p /www/wwwroot/ecommerce-backend || sudo mkdir -p /www/wwwroot/ecommerce-backend
          
          # Wait a moment for scp to complete
          sleep 2
          
          # Stop the existing service first
          sudo systemctl stop ecommerce-backend || true
          
          # Debug: List files in target directory
          echo "=== Files in deployment directory ==="
          ls -la /www/wwwroot/ecommerce-backend/ || sudo ls -la /www/wwwroot/ecommerce-backend/
          
          # Check for the NEWLY uploaded binary (uploaded with .new extension)
          if [ ! -f /www/wwwroot/ecommerce-backend/ecommerce-backend.new ]; then
            echo "ERROR: New binary file not found at /www/wwwroot/ecommerce-backend/ecommerce-backend.new"
            echo "Checking what files exist..."
            ls -la /www/wwwroot/ecommerce-backend/ || sudo ls -la /www/wwwroot/ecommerce-backend/
            exit 1
          fi
          
          echo "✅ New binary found, backing up old one..."
          
          # Backup current binary if it exists
          if [ -f /www/wwwroot/ecommerce-backend/ecommerce-backend ]; then
            echo "Backing up existing binary..."
            sudo mv /www/wwwroot/ecommerce-backend/ecommerce-backend /www/wwwroot/ecommerce-backend/ecommerce-backend.backup.$(date +%Y%m%d_%H%M%S)
          fi
          
          # Move new binary to final location
          echo "Moving new binary to final location..."
          sudo mv /www/wwwroot/ecommerce-backend/ecommerce-backend.new /www/wwwroot/ecommerce-backend/ecommerce-backend
          
          # Set permissions
          echo "Setting permissions..."
          sudo chmod +x /www/wwwroot/ecommerce-backend/ecommerce-backend
          sudo chown www:www /www/wwwroot/ecommerce-backend/ecommerce-backend
          
          # Verify it's executable and exists
          if [ ! -f /www/wwwroot/ecommerce-backend/ecommerce-backend ]; then
            echo "ERROR: Binary file missing after move"
            exit 1
          fi
          
          if [ ! -x /www/wwwroot/ecommerce-backend/ecommerce-backend ]; then
            echo "ERROR: Binary is not executable after chmod"
            exit 1
          fi
          
          echo "✅ Binary is ready"
          
          # Ensure uploads directory exists with proper permissions
          sudo mkdir -p /www/wwwroot/ecommerce-backend/uploads/products
          sudo mkdir -p /www/wwwroot/ecommerce-backend/uploads/slider
          sudo chown -R www:www /www/wwwroot/ecommerce-backend/uploads
          
          # Restart the service (restart handles stop+start better)
          sudo systemctl restart ecommerce-backend
          sudo systemctl enable ecommerce-backend
          
          # Wait for service to fully start
          sleep 3
          
          # Check service status
          sudo systemctl is-active ecommerce-backend || {
            echo "Service failed to start. Checking logs:"
            sudo journalctl -u ecommerce-backend -n 20 --no-pager
            exit 1
          }
          
          # Test the API with retries
          for i in {1..5}; do
            sleep 2
            if curl -f http://localhost:8080/health > /dev/null 2>&1; then
              echo "✅ Health check passed"
              break
            fi
            echo "Attempt $i: Health check failed, retrying..."
          done
          
          # Final status check
          sudo systemctl status ecommerce-backend --no-pager -l
