name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[test]') || contains(github.event.head_commit.message, '[run-tests]')
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Go application
      run: |
        go mod download
        go build -o ecommerce-backend main.go
    
    - name: Upload binary to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "ecommerce-backend"
        target: "/www/wwwroot/ecommerce-backend/"
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Create directory if it doesn't exist (aaPanel structure)
          sudo mkdir -p /www/wwwroot/ecommerce-backend
          
          # Stop the existing service
          sudo systemctl stop ecommerce-backend || true
          
          # Backup current binary
          if [ -f /www/wwwroot/ecommerce-backend/ecommerce-backend ]; then
            sudo mv /www/wwwroot/ecommerce-backend/ecommerce-backend /www/wwwroot/ecommerce-backend/ecommerce-backend.backup.$(date +%Y%m%d_%H%M%S)
          fi
          
          # The binary was uploaded to /www/wwwroot/ecommerce-backend/ by scp-action
          # Verify the binary exists and set permissions
          if [ -f /www/wwwroot/ecommerce-backend/ecommerce-backend ]; then
            sudo chmod +x /www/wwwroot/ecommerce-backend/ecommerce-backend
            sudo chown www:www /www/wwwroot/ecommerce-backend/ecommerce-backend
          else
            echo "ERROR: Binary file not found after upload!"
            exit 1
          fi
          
          # Ensure uploads directory exists with proper permissions
          sudo mkdir -p /www/wwwroot/ecommerce-backend/uploads/products
          sudo mkdir -p /www/wwwroot/ecommerce-backend/uploads/slider
          sudo chown -R www:www /www/wwwroot/ecommerce-backend/uploads
          
          # Restart the service (restart handles stop+start better)
          sudo systemctl restart ecommerce-backend
          sudo systemctl enable ecommerce-backend
          
          # Wait for service to fully start
          sleep 3
          
          # Check service status
          sudo systemctl is-active ecommerce-backend || {
            echo "Service failed to start. Checking logs:"
            sudo journalctl -u ecommerce-backend -n 20 --no-pager
            exit 1
          }
          
          # Test the API with retries
          for i in {1..5}; do
            sleep 2
            if curl -f http://localhost:8080/health > /dev/null 2>&1; then
              echo "✅ Health check passed"
              break
            fi
            echo "Attempt $i: Health check failed, retrying..."
          done
          
          # Final status check
          sudo systemctl status ecommerce-backend --no-pager -l
