name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Go application
      run: |
        go mod download
        go build -o ecommerce-backend main.go
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Create directory if it doesn't exist
          mkdir -p /var/www/ecommerce-backend
          
          # Stop the existing service
          sudo systemctl stop ecommerce-backend || true
          
          # Backup current binary
          if [ -f /var/www/ecommerce-backend/ecommerce-backend ]; then
            sudo mv /var/www/ecommerce-backend/ecommerce-backend /var/www/ecommerce-backend/ecommerce-backend.backup.$(date +%Y%m%d_%H%M%S)
          fi
          
          # Copy new binary
          sudo cp ecommerce-backend /var/www/ecommerce-backend/
          sudo chmod +x /var/www/ecommerce-backend/ecommerce-backend
          
          # Copy environment file if it doesn't exist
          if [ ! -f /var/www/ecommerce-backend/.env ]; then
            sudo cp env.example /var/www/ecommerce-backend/.env
          fi
          
          # Start the service
          sudo systemctl start ecommerce-backend
          sudo systemctl enable ecommerce-backend
          
          # Check service status
          sudo systemctl status ecommerce-backend
